### 1. 라이브러리 설치

1.1 판다스, 넘파이, 맷플롯립 라이브러리 설치

In [2]:
# !는 주피터 노트북에서 OS 명령을 실행한다.
!pip install pandas numpy matplotlib

Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.1.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (1.19.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (3.2.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib) (1.3.1)

### 2. 판다스 라이브러리 사용법

2.1 판다스 라이브러리 불러오기

In [3]:
#판다스 라이브러리를 실행환경으로 불러오기 위해 import 명령을 사용한다.
# import 라이브러리명 as 라이브러리 약칭
import pandas as pd

2.2 딕셔너리(dictionary)를 시리즈(series)로 변환

In [5]:
# {key:value} 구조를 갖는 딕셔너리를 만들고, 변수 dict_data에 저장한다.
dict_data = {'a':1,'b':2,'c':3}

#판다스 Series() 함수로 딕셔너리(dict_data)를 시리즈로 변환한다.
#Series() 함수가 반환한 시리즈 객체를 변수 sr에 저장한다.
sr = pd.Series(dict_data)

#변수 sr의 자료형 출력
print(type(sr))
print('\n')

#변수 sr에 저장되어 있는 시리즈 객체를 출력한다.
print(sr)

<class 'pandas.core.series.Series'>


a    1
b    2
c    3
dtype: int64

2.3 파이썬 리스트(list)를 시리즈(series)로 변환

In [6]:
#파이썬 리스트는 어떠한 데이터형도 포함할 수 있다.
list_data = ['2019-01-02', 3.14, 'ABC', 100, True]

#판다스 Series() 함수로 리스트(list_data)를 시리즈로 변환한다.
#Sereis() 함수가 반환한 시리즈 객체를 변수 sr에 저장한다.
sr = pd.Series(list_data)
print(sr)

0    2019-01-02
1          3.14
2           ABC
3           100
4          True
dtype: object

2.4 시리즈의 인덱스와 데이터 확인하기

In [9]:
#시리즈의 index 속성은 인덱스 정보를 제공한다.
#인덱스 범위(Range Index)는 0부터 시작하고 마지막 인데스값(stop)은 포함되지 않는다.
print(sr.index)
print('\n')

#시리즈의 values 속성으로 데이터 배열을 불러온다.
print(sr.values)

RangeIndex(start=0, stop=5, step=1)


['2019-01-02' 3.14 'ABC' 100 True]

2.5 파이썬 튜플(tuple)을 시리즈(series)로 변환

In [14]:
# 튜플을 변수 tup_data에 저장한다.
tup_data = ('영인', '2010-05-01', '여', True)

# Series() 함수로 튜블(tup_data)를 시리즈로 변환한다.
# index 옵션에 인덱스 이름을 지정한다.
sr = pd.Series(tup_data, index=['이름', '생년월일', '성별', '학생여부'])
print(sr)

이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object

2.6 시리즈 원소 선택하기

In [16]:
#원소를 1개 선택
print(sr[0])        #정수형 위치 인덱스를 활용
print(sr['이름'])   #인덱스 이름을 활용

영인
영인

In [17]:
#여러 개의 원소를 선택 (인덱스 리스트 활용)
print(sr[[1,2]])
print('\n')
print(sr[['생년월일', '성별']])

생년월일    2010-05-01
성별               여
dtype: object


생년월일    2010-05-01
성별               여
dtype: object

In [18]:
#여러 개의 원소를 선택 (인덱스 범위 지정)
# 정수형 인덱스 범위의 마지막 값은 포함되지 않는다.
print(sr[1 : 2])
print('\n')
# 인덱스 이름을 사용할 때는 마지막 값이 포함된다.
print(sr['생년월일':'성별'])

생년월일    2010-05-01
dtype: object


생년월일    2010-05-01
성별               여
dtype: object

2.7 딕셔너리(dictionary)를 데이터프레임으로 변환

In [20]:
# 열이름은 key로 하고, 리스트를 value로 갖는 딕셔너리를 정의한다.
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}

# 판다스 DataFrame() 함수로 딕셔너리를 데이터프레임으로 변환한다.
# DataFrame() 함수가 변환한 데이터프레임 객체를 변수 df에 저장한다.
df = pd.DataFrame(dict_data)

#df의 자료형 출력한다.
print(type(df))
print('\n')
#변수 df에 저장되어 있는 데이터프레임 객체를 출력
print(df)

<class 'pandas.core.frame.DataFrame'>


   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

2.8 여러개의 리스트(list)를 데이터프레임으로 변환

In [22]:
#먼저 개수가 같은 3개의 리스트를 생성한다.
names = ['Bob', 'Jessica', 'Mary', 'John', 'Mel']
births = [968, 155, 77, 578, 973]
custom = [1, 5, 25, 13, 23232]

#zip()는 길이가 같은 리스트 등의 요소를 묶어준다.
#list()는 리스트 자료형으로 변환해준다.
BabyDataSet = list(zip(names,births))

#pd.DataFrame(data=데이터셋, columns=컬럼명)으로 데이터프레임이 생성된다.
df = pd.DataFrame(data=BabyDataSet, columns=['Names', 'Births'])

#데이터프레임의 상위 5개의 행을 출력한다.
df.head()

     Names  Births
0      Bob     968
1  Jessica     155
2     Mary      77
3     John     578
4      Mel     973

2.9 데이터프레임의 기본 정보 출력하기

In [24]:
#데이터프레임의 타입(type) 정보 --> 데이터 타입을 알 수 있다.
print(df.dtypes)
print("-----------")

#데이터프레임의 index 정보 --> 행의 수를 알 수 있다.
print(df.index)
print("-----------")

#데이터프레임의 열의 정보 --> 칼럼명을 알 수 있다.
print(df.columns)
print("-----------")
print(df.values)

Names     object
Births     int64
dtype: object
-----------
RangeIndex(start=0, stop=5, step=1)
-----------
Index(['Names', 'Births'], dtype='object')
-----------
[['Bob' 968]
 ['Jessica' 155]
 ['Mary' 77]
 ['John' 578]
 ['Mel' 973]]

2.10 데이터프레임의 특정 행ㅇ과 열 선택하기

In [25]:
#데이터프레임에서 하나의 열을 선택한다.
df['Names']

0        Bob
1    Jessica
2       Mary
3       John
4        Mel
Name: Names, dtype: object

2.11 데이터프레임의 인덱스 선택하기

In [26]:
#데이터프레임의 특정 행(인덱스)를 선택한다.
#df[start:stop] start인덱스는 0부터 시작, (stop인덱스-1) 까지 행이 선택된다.
df[0:3]

     Names  Births
0      Bob     968
1  Jessica     155
2     Mary      77

2.12 데이터프레임의 필터링 기능

In [27]:
#Births 열에서 100보다 큰 데이터를 필터링한다.
df[df['Births']>100]

     Names  Births
0      Bob     968
1  Jessica     155
3     John     578
4      Mel     973

2.13 평균값을 구하는 기능

In [28]:
#mean()는 각 열의 데이터타입을 체크한 뒤, 수치형 데이터에 대해 평균을 구한다.
df.mean()

Births    550.2
dtype: float64